version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@1.0.15
jobs:
 build-and-run:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
 deploy2s3: 
    docker: 
      - image: cimg/python:3.6
    steps:
      - aws-s3/copy: #invokes the sync command declared in the s3 orb
          arguments: '--dry-run'
          from: bucket/build_asset.txt
          to: 's3:/cicd-hackney-works-theme-artifact'
workflows:
    build-and-run:
      jobs:
        - build-and-run
        - deploy2s3
