version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@x.y
jobs:
 build-and-run:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
 store_artifacts:
          path: /home/circleci/project
workflows:
    build-and-run:
      jobs:
        - build-and-run
        - store_artifacts
